### PR TITLE
Test destinations

### PR DESCRIPTION
**Pull request by PMMcode**
New script added to check specified destination

### CODE REVIEW

**Review by PMMcode — COMMENTED** [review]
That is the initial commit of the change

**Review by GSCFJD — APPROVED** [review]
Seems ok

**Review by GSCFJD — CHANGES_REQUESTED** [review]
No need to have that line added

**Review by GSCFJD — APPROVED** [review]
Sample config added

**Review by GSCFJD — APPROVED** [review]
Good catch

**Comment by GSCFJD** [comment]
Change .gitignore back to previous and we are good.

**Pull request closed without merging**
